export const basePrompt = `<boltArtifact id="project-import" title="Python Django Starter Project">

<boltAction type="file" filePath="requirements.txt">
django==5.0.2
djangorestframework==3.15.1
</boltAction>

<boltAction type="file" filePath="manage.py">
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
</boltAction>

<boltAction type="file" filePath="myproject/__init__.py"></boltAction>

<boltAction type="file" filePath="myproject/asgi.py">
import os
from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')
application = get_asgi_application()
</boltAction>

<boltAction type="file" filePath="myproject/settings.py">
"""
Django settings for myproject.
Generated by ChatGPT for Bharat 🚀
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-test-key'
DEBUG = True
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
</boltAction>

<boltAction type="file" filePath="myproject/urls.py">
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
</boltAction>

<boltAction type="file" filePath="myproject/wsgi.py">
import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')
application = get_wsgi_application()
</boltAction>

<boltAction type="file" filePath="main/__init__.py"></boltAction>

<boltAction type="file" filePath="main/admin.py">
from django.contrib import admin
from .models import Message

admin.site.register(Message)
</boltAction>

<boltAction type="file" filePath="main/apps.py">
from django.apps import AppConfig

class MainConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'main'
</boltAction>

<boltAction type="file" filePath="main/models.py">
from django.db import models

class Message(models.Model):
    text = models.CharField(max_length=255)

    def __str__(self):
        return self.text
</boltAction>

<boltAction type="file" filePath="main/views.py">
from rest_framework.decorators import api_view
from rest_framework.response import Response

@api_view(['GET'])
def home(request):
    return Response({"message": "Hello from Django + DRF!"})
</boltAction>

<boltAction type="file" filePath="main/urls.py">
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]
</boltAction>

<boltAction type="file" filePath=".gitignore">
__pycache__/
db.sqlite3
*.pyc
*.log
.env
</boltAction>

<boltAction type="file" filePath="README.md">
# 🐍 Django Starter Project

A simple **Django + Django REST Framework** project.

### ▶️ Run Instructions

1. Create virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate   # or venv\\Scripts\\activate on Windows
   \`\`\`

2. Install dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

3. Run server:
   \`\`\`bash
   python manage.py runserver
   \`\`\`

4. Visit [http://localhost:8000](http://localhost:8000)
</boltAction>

</boltArtifact>`;
